### ISSUE TITLE
Add General Code to a Source File

### ISSUE THREAD

**Issue by TrevorCash** [JhnW/devana#12]
Hi @JhnW ,

I have a SouceFile() object (a header file)  I have already added source objects to (functions in namespaces etc).  Now I am trying to add some general code (or raw text) to the header (within the header guards).  I am trying to add:

`#define MYDEFINE arbritrarytexthere`

I have tried using CodeContainer() and adding that to the SourceFile content . but it says that is an abstract class - do I need to subclass it or is there another way of adding very general text to a SourceFile() object. 

Thanks for the help,
-Trevor

**Comment by JhnW** [comment]
Hi Trevor.
Yes, it exist. Please find [StubType](https://jhnw.github.io/devana/api/devana.code_generation.html#module-devana.code_generation.stubtypel).

**Comment by TrevorCash** [comment]
Hi JhnW,
Thanks for the help - It is working
